apiVersion: v1
kind: Service
metadata:
  name: shoppingcartapp-service
  namespace:   
spec:
  selector:
    app: shoppingcartapp
  ports:
    - port: 85      
      targetPort: 8090
  type: LoadBalancer
